"""create demand ledger schema

Revision ID: 09f0c4196760
Revises:
Create Date: 2026-09-29 21:57:37.768891

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "09f0c4196760"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competitor_shares",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mega_segment_id", sa.String(length=10), nullable=False),
        sa.Column("competitor", sa.String(length=80), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("share_pct", sa.Float(), nullable=False),
        sa.Column("value_eur", sa.Float(), nullable=False),
        sa.Column("trend", sa.String(length=30), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("competitor_shares", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_competitor_shares_mega_segment_id"), ["mega_segment_id"], unique=False
        )

    op.create_table(
        "demo_clock",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "grower_potential",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("variety", sa.String(length=80), nullable=True),
        sa.Column("owner", sa.String(length=20), nullable=False),
        sa.Column("hectares", sa.Float(), nullable=False),
        sa.Column("density", sa.Float(), nullable=False),
        sa.Column("region", sa.String(length=80), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rep_track_records",
        sa.Column("user_id", sa.String(length=40), nullable=False),
        sa.Column("entries_resolved", sa.Integer(), nullable=False),
        sa.Column("bias_pct", sa.Float(), nullable=True),
        sa.Column("claim_hit_rate", sa.Float(), nullable=True),
        sa.Column("range_coverage", sa.Float(), nullable=True),
        sa.Column("confirmed", sa.Integer(), nullable=False),
        sa.Column("contradicted", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "segments",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("cycle", sa.String(length=60), nullable=True),
        sa.Column("color", sa.String(length=30), nullable=True),
        sa.Column("ecology", sa.String(length=60), nullable=True),
        sa.Column("mega_segment_id", sa.String(length=10), nullable=False),
        sa.Column("mega_segment_desc", sa.String(length=100), nullable=False),
        sa.Column("profile", sa.String(length=30), nullable=False),
        sa.Column("owner_id", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("segments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_segments_mega_segment_id"), ["mega_segment_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_segments_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "demand_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=40), nullable=False),
        sa.Column("segment_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("justification", sa.Text(), nullable=True),
        sa.Column("impact", sa.JSON(), nullable=True),
        sa.Column("flags", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("triage", sa.JSON(), nullable=True),
        sa.Column("reviewed_by", sa.String(length=40), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["segments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("demand_entries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_demand_entries_segment_id"), ["segment_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_demand_entries_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_demand_entries_user_id"), ["user_id"], unique=False)

    op.create_table(
        "market_years",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("segment_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("hectares", sa.Float(), nullable=False),
        sa.Column("qty_ks", sa.Float(), nullable=False),
        sa.Column("density", sa.Float(), nullable=False),
        sa.Column("price_exseed", sa.Float(), nullable=False),
        sa.Column("price_farmgate", sa.Float(), nullable=False),
        sa.Column("notes", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["segments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("segment_id", "year"),
    )
    with op.batch_alter_table("market_years", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_market_years_segment_id"), ["segment_id"], unique=False)

    op.create_table(
        "monthly_actuals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("segment_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("qty_ks", sa.Float(), nullable=False),
        sa.Column("value_eur", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["segments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("segment_id", "year", "month"),
    )
    with op.batch_alter_table("monthly_actuals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_monthly_actuals_segment_id"), ["segment_id"], unique=False)

    op.create_table(
        "monthly_plan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("segment_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("qty_ks", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["segments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("segment_id", "year", "month"),
    )
    with op.batch_alter_table("monthly_plan", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_monthly_plan_segment_id"), ["segment_id"], unique=False)

    op.create_table(
        "plan_years",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("segment_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("qty_ks", sa.Float(), nullable=False),
        sa.Column("value_eur", sa.Float(), nullable=False),
        sa.Column("net_price", sa.Float(), nullable=False),
        sa.Column("fpi_qty_ks", sa.Float(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["segments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("segment_id", "year"),
    )
    with op.batch_alter_table("plan_years", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_plan_years_segment_id"), ["segment_id"], unique=False)

    op.create_table(
        "claims",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entry_id", sa.String(length=36), nullable=False),
        sa.Column("driver", sa.String(length=40), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("magnitude", sa.Float(), nullable=True),
        sa.Column("competitor", sa.String(length=80), nullable=True),
        sa.Column("variety", sa.String(length=80), nullable=True),
        sa.Column("evidence_source", sa.String(length=40), nullable=True),
        sa.Column("verifiable", sa.Float(), nullable=True),
        sa.Column("consistent_with_notes", sa.Float(), nullable=True),
        sa.Column("specificity", sa.Float(), nullable=True),
        sa.Column("addresses_flags", sa.Float(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("decisions", sa.JSON(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("signal", sa.String(length=40), nullable=False),
        sa.Column("check_year", sa.Integer(), nullable=False),
        sa.Column("check_month", sa.Integer(), nullable=False),
        sa.Column("resolution", sa.String(length=20), nullable=False),
        sa.Column("resolution_detail", sa.JSON(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["demand_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entry_id"),
    )
    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_claims_resolution"), ["resolution"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_claims_resolution"))

    op.drop_table("claims")
    with op.batch_alter_table("plan_years", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plan_years_segment_id"))

    op.drop_table("plan_years")
    with op.batch_alter_table("monthly_plan", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_monthly_plan_segment_id"))

    op.drop_table("monthly_plan")
    with op.batch_alter_table("monthly_actuals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_monthly_actuals_segment_id"))

    op.drop_table("monthly_actuals")
    with op.batch_alter_table("market_years", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_market_years_segment_id"))

    op.drop_table("market_years")
    with op.batch_alter_table("demand_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_demand_entries_user_id"))
        batch_op.drop_index(batch_op.f("ix_demand_entries_status"))
        batch_op.drop_index(batch_op.f("ix_demand_entries_segment_id"))

    op.drop_table("demand_entries")
    with op.batch_alter_table("segments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_segments_owner_id"))
        batch_op.drop_index(batch_op.f("ix_segments_mega_segment_id"))

    op.drop_table("segments")
    op.drop_table("rep_track_records")
    op.drop_table("grower_potential")
    op.drop_table("demo_clock")
    with op.batch_alter_table("competitor_shares", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_competitor_shares_mega_segment_id"))

    op.drop_table("competitor_shares")
    # ### end Alembic commands ###
