"""chat actions and entry notes

Revision ID: a7bff5427ff3
Revises: ee394ecde232
Create Date: 2026-10-01 13:29:43.364193

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = 'a7bff5427ff3'
down_revision: Union[str, None] = 'ee394ecde232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('invocation_id', sa.String(length=128), nullable=False),
    sa.Column('tool', sa.String(length=60), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('args', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_actions'))
    )
    with op.batch_alter_table('chat_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_actions_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_actions_user_id'), ['user_id'], unique=False)

    op.create_table('entry_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('via', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['demand_entries.id'], name=op.f('fk_entry_notes_entry_id_demand_entries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entry_notes'))
    )
    with op.batch_alter_table('entry_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entry_notes_entry_id'), ['entry_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entry_notes_entry_id'))

    op.drop_table('entry_notes')
    with op.batch_alter_table('chat_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_actions_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_actions_target_id'))

    op.drop_table('chat_actions')
    # ### end Alembic commands ###
