"""sac ibp forecasts and variety map

Revision ID: ee394ecde232
Revises: 3c1d7e2a9b40
Create Date: 2026-10-01 12:23:11.457088

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = 'ee394ecde232'
down_revision: Union[str, None] = '3c1d7e2a9b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ibp_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('variety', sa.String(length=120), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.String(length=40), nullable=False),
    sa.Column('qty_ks', sa.Float(), nullable=False),
    sa.Column('value_usd', sa.Float(), nullable=True),
    sa.Column('planner_id', sa.String(length=200), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], name=op.f('fk_ibp_forecasts_segment_id_segments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ibp_forecasts')),
    sa.UniqueConstraint('country_code', 'segment_id', 'variety', 'year', 'month', 'snapshot', name='uq_ibp_forecasts_key')
    )
    with op.batch_alter_table('ibp_forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ibp_forecasts_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_ibp_forecasts_segment_id'), ['segment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ibp_forecasts_snapshot'), ['snapshot'], unique=False)

    op.create_table('variety_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('variety', sa.String(length=120), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], name=op.f('fk_variety_map_segment_id_segments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variety_map')),
    sa.UniqueConstraint('country_code', 'variety', name='uq_variety_map_country_variety')
    )
    with op.batch_alter_table('variety_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_variety_map_country_code'), ['country_code'], unique=False)

    with op.batch_alter_table('demand_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snapshot', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand_entries', schema=None) as batch_op:
        batch_op.drop_column('snapshot')

    with op.batch_alter_table('variety_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_variety_map_country_code'))

    op.drop_table('variety_map')
    with op.batch_alter_table('ibp_forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ibp_forecasts_snapshot'))
        batch_op.drop_index(batch_op.f('ix_ibp_forecasts_segment_id'))
        batch_op.drop_index(batch_op.f('ix_ibp_forecasts_country_code'))

    op.drop_table('ibp_forecasts')
    # ### end Alembic commands ###
